- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent
    
- name: Turn swap off
  shell: swapoff -a
  
- name: disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
    
- name: Set Enforce
  command: setenforce 0
  ignore_errors: True
  
- name: copy chronyd config
  template:
    src: chrony.conf
    dest: /etc/chrony.conf
    
- name: Start chronyd
  systemd:
    name: chronyd
    state: started
    enabled: true
    
- name: Install k8s packages
  become: yes
  yum:
    name: "{{ packages }}"
    enablerepo: k8s-repo
    state: present
  vars:
    packages:
    - kubeadm
    - kubectl
    - kubelet
    
- name: Add vm swappiness
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'vm.swappiness = 0'
    state: present
    create: yes
    
- name: Add vm overcommit_memory
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'vm.overcommit_memory = 1'
    state: present
    create: yes
    
- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present
  register: br_netfilter
  
- name: Add netbridge config ip4
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'net.bridge.bridge-nf-call-iptables = 1'
    state: present
    create: yes
    
- name: Add net.ipv4.ip_forward
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'net.ipv4.ip_forward = 1'
    state: present
    create: yes
    
- name: Increase net ipv4 tcp_max_syn_backlog
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'net.ipv4.tcp_max_syn_backlog = 2621440'
    state: present
    create: yes
    
- name: update sysctl
  command: sysctl --system
  
- name: copy kubelet config
  template:
    src: kubelet
    dest: /etc/sysconfig/kubelet
    
- name: Start kubelet
  systemd:
    name: kubelet
    state: started
    enabled: true
  
