- name: Install haproxy
  become: yes
  yum:
    name: haproxy
    enablerepo: k8s-repo
    state: present

- name: setup haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    
- name: start haproxy
  systemd:
    name: haproxy
    state: started
    enabled: true
